services:
  redis:
    image: redis:7-alpine
    restart: always

  state-service:
    build: .
    command: uvicorn bot_service.state_service:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  calorie-service:
    build: .
    command: uvicorn bot_service.calorie_service:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - .:/app

  bot-app:
    build: .
    command: python bot_service/bot_app.py
    depends_on:
      - state-service
      - calorie-service
    env_file:
      - bot_service/.env
    environment:
      - STATE_SERVICE_URL=http://state-service:8000
      - CALORIE_SERVICE_URL=http://calorie-service:8001
      - PYTHONUNBUFFERED=1